# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Teste_Plugin_Buffer
                                 A QGIS plugin
 Exemplo de um plugin que aplica um buffer numa camada vetorial 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-04
        copyright            : (C) 2025 by ADRIAN ARTURO 
        email                : adrianvillegas778@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Teste_Plugin_Buffer class from file Teste_Plugin_Buffer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .teste_buffer import Teste_Plugin_Buffer
    return Teste_Plugin_Buffer(iface)
